{
 "title": "Gateway",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><center><u>Gateway Health Dashboard"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 2 },
   "options": {
    "content": "<h2><center>Heathrow</center>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 10, "y": 2 },
   "options": {
    "content": "<h2><center>Gothenburg</center>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_function_status{appliance_name=\"lhr - purple80\", name=\"gateway\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_function_status{appliance_name=\"lhr - purple81\", name=\"gateway\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_function_status{appliance_name=\"got - purple1\",name=\"gateway\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_function_status{appliance_name=\"got - purple2\", name=\"gateway\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "description": "Gateway function health",
   "gridPos": { "h": 1, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_function_status{appliance_name=\"lhr - purple80\",name=\"gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Gateway function health",
   "gridPos": { "h": 1, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_function_status{appliance_name=\"lhr - purple81\",name=\"gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Gateway function health",
   "gridPos": { "h": 1, "w": 5, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_function_status{appliance_name=\"got - purple1\",name=\"gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Gateway function health",
   "gridPos": { "h": 1, "w": 5, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_function_status{appliance_name=\"got - purple2\",name=\"gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Appliance health",
   "gridPos": { "h": 1, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_status{appliance_name=\"lhr - purple80\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Appliance health",
   "gridPos": { "h": 1, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_status{appliance_name=\"lhr - purple81\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Appliance health",
   "gridPos": { "h": 1, "w": 5, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_status{appliance_name=\"got - purple1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Appliance health",
   "gridPos": { "h": 1, "w": 5, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_status{appliance_name=\"got - purple2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs being successfully exported (per 5min)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(apn_audit_logs {appliance_name=\"lhr - purple80\",type=\"removed\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "increase(apn_audit_logs {appliance_name=\"lhr - purple81\",type=\"removed\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "increase(apn_audit_logs {appliance_name=\"got - purple1\",type=\"removed\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "increase(apn_audit_logs {appliance_name=\"got - purple2\",type=\"removed\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "Average CPU usage % (1 min)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(apn_cpu_usage_percent{appliance_name=\"lhr - purple80\"} [$__interval])",
     "legendFormat": " "
    },
    {
     "expr": "avg_over_time(apn_cpu_usage_percent{appliance_name=\"lhr - purple81\"} [$__interval])",
     "legendFormat": " "
    },
    {
     "expr": "avg_over_time(apn_cpu_usage_percent{appliance_name=\"got - purple1\"} [$__interval])",
     "legendFormat": " "
    },
    {
     "expr": "avg_over_time(apn_cpu_usage_percent{appliance_name=\"got - purple2\"} [$__interval])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "NIC throughputs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg_over_time(apn_network_interface_speed {measure=\"rx_speed\",appliance_name=\"lhr - purple80\"} [$__interval])",
     "legendFormat": "{{job}} rx {{name}}"
    },
    {
     "expr": "avg_over_time(apn_network_interface_speed {measure=\"tx_speed\",appliance_name=\"lhr - purple80\"} [$__interval])",
     "legendFormat": "{{job}} rx {{name}}"
    },
    {
     "expr": "avg_over_time(apn_network_interface_speed {measure=\"rx_speed\",appliance_name=\"lhr - purple81\"} [$__interval])",
     "legendFormat": "{{job}} rx {{name}}"
    },
    {
     "expr": "avg_over_time(apn_network_interface_speed {measure=\"tx_speed\",appliance_name=\"lhr - purple81\"} [$__interval])",
     "legendFormat": "{{job}} tx {{name}}"
    }
   ]
  },
  {
   "title": "NIC throughputs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg_over_time(apn_network_interface_speed {measure=\"rx_speed\",appliance_name=\"got - purple1\"} [$__interval])",
     "legendFormat": "{{job}} rx {{name}}"
    },
    {
     "expr": "avg_over_time(apn_network_interface_speed {measure=\"tx_speed\",appliance_name=\"got - purple1\"} [$__interval])",
     "legendFormat": "{{job}} tx {{name}}"
    },
    {
     "expr": "avg_over_time(apn_network_interface_speed {measure=\"rx_speed\",appliance_name=\"got - purple2\"} [$__interval])",
     "legendFormat": "{{job}} rx {{name}}"
    },
    {
     "expr": "avg_over_time(apn_network_interface_speed {measure=\"tx_speed\",appliance_name=\"got - purple2\"} [$__interval])",
     "legendFormat": "{{job}} tx {{name}}"
    }
   ]
  },
  {
   "title": "Gateways session split",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gw_vpn_sessions {appliance_name=\"lhr - purple80\"} ",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "gw_vpn_sessions {appliance_name=\"lhr - purple81\"}",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "Gateways session split",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gw_vpn_sessions {appliance_name=\"got - purple1\"} ",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "gw_vpn_sessions {appliance_name=\"got - purple2\"}",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "Firewall rules active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "avg_over_time(gw_vpn_rules {appliance_name=\"lhr - purple80\"} [$__interval])",
     "legendFormat": "{{appliance_name}} {{proto}}"
    },
    {
     "expr": "avg_over_time(gw_vpn_rules {appliance_name=\"lhr - purple81\"} [$__interval])",
     "legendFormat": "{{appliance_name}} {{proto}}"
    }
   ]
  },
  {
   "title": "Firewall rules active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 32 },
   "targets": [
    {
     "expr": "avg_over_time(gw_vpn_rules {appliance_name=\"got - purple1\"} [$__interval])",
     "legendFormat": "{{appliance_name}} {{proto}}"
    },
    {
     "expr": "avg_over_time(gw_vpn_rules {appliance_name=\"got - purple2\"} [$__interval])",
     "legendFormat": "{{appliance_name}} {{proto}}"
    }
   ]
  },
  {
   "title": "URL access ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "avg_over_time(gw_http_open_connection {appliance_name=\"lhr - purple80\",type=\"active\"} [$__interval])\n",
     "legendFormat": "{{appliance_name}} {{type}}"
    },
    {
     "expr": "rate(gw_http_requests {appliance_name=\"lhr - purple80\"} [$__interval])*60\n",
     "legendFormat": "{{job}} req/min"
    },
    {
     "expr": "avg_over_time(gw_http_open_connection {appliance_name=\"lhr - purple81\",type=\"active\"} [$__interval])\n",
     "legendFormat": "{{appliance_name}} {{type}}"
    },
    {
     "expr": "rate(gw_http_requests {appliance_name=\"lhr - purple81\"} [$__interval])*60\n",
     "legendFormat": "{{job}} req/min"
    }
   ]
  },
  {
   "title": "URL access ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 40 },
   "targets": [
    {
     "expr": "avg_over_time(gw_http_open_connection {appliance_name=\"got - purple1\",type=\"active\"} [$__interval])\n",
     "legendFormat": "{{appliance_name}} {{type}}"
    },
    {
     "expr": "rate(gw_http_requests {appliance_name=\"got - purple1\"} [$__interval])*60\n",
     "legendFormat": "{{job}} req/min"
    },
    {
     "expr": "avg_over_time(gw_http_open_connection {appliance_name=\"got - purple2\",type=\"active\"} [$__interval])\n",
     "legendFormat": "{{appliance_name}} {{type}}"
    },
    {
     "expr": "rate(gw_http_requests {appliance_name=\"got - purple2\"} [$__interval])*60\n",
     "legendFormat": "{{job}} req/min"
    }
   ]
  },
  {
   "title": "Java heap (memory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "gw_sessiond_heap {appliance_name=\"lhr - purple80\",measure=\"used\"}",
     "legendFormat": "{{appliance_name}} {{type}}"
    },
    {
     "expr": "gw_sessiond_heap {appliance_name=\"lhr - purple81\",measure=\"used\"}",
     "legendFormat": "{{appliance_name}} {{type}}"
    }
   ]
  },
  {
   "title": "Java heap (memory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "gw_sessiond_heap {appliance_name=\"got - purple1\",measure=\"used\"}",
     "legendFormat": "{{appliance_name}} {{type}}"
    },
    {
     "expr": "gw_sessiond_heap {appliance_name=\"got - purple2\",measure=\"used\"}",
     "legendFormat": "{{appliance_name}} {{type}}"
    }
   ]
  },
  {
   "title": "Event queue size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "gw_event_queue_period_peak {appliance_name=\"lhr - purple80\"}",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "gw_event_queue_period_peak {appliance_name=\"lhr - purple81\"}",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "gw_event_queue_period_peak {appliance_name=\"got - purple1\"}",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "gw_event_queue_period_peak {appliance_name=\"got - purple2\"}",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "Average time per event (mS)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gw_session_event_timing {measure=\"accumulated\", appliance_name=\"lhr - purple80\"} / ignoring(measure) gw_session_event_count {appliance_name=\"lhr - purple80\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Average time per event (mS)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gw_session_event_timing {measure=\"accumulated\", appliance_name=\"lhr - purple81\"} / ignoring(measure) gw_session_event_count {appliance_name=\"lhr - purple81\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Average time per event (mS)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gw_session_event_timing {measure=\"accumulated\", appliance_name=\"got - purple1\"} / ignoring(measure) gw_session_event_count {appliance_name=\"got - purple1\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Average time per event (mS)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gw_session_event_timing {measure=\"accumulated\", appliance_name=\"got - purple2\"} / ignoring(measure) gw_session_event_count {appliance_name=\"got - purple2\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Time to sign-in",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "gw_session_event_timing {appliance_name=\"lhr - purple80\",measure=\"average\",type=\"login\"}",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "gw_session_event_timing {appliance_name=\"lhr - purple81\",measure=\"average\",type=\"login\"}",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "gw_session_event_timing {appliance_name=\"got - purple1\",measure=\"average\",type=\"login\"}",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "gw_session_event_timing {appliance_name=\"got - purple2\",measure=\"average\",type=\"login\"}",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "description": "Mean available memory usage",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apn_memory {appliance_name=\"lhr - purple80\",measure=\"percent\"}",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "apn_memory {appliance_name=\"lhr - purple81\", measure=\"percent\"}",
     "legendFormat": " {{appliance_name}}"
    },
    {
     "expr": "apn_memory {appliance_name=\"got - purple1\", measure=\"percent\"}",
     "legendFormat": " {{appliance_name}}"
    },
    {
     "expr": "apn_memory {appliance_name=\"got - purple2\", measure=\"percent\"}",
     "legendFormat": " {{appliance_name}}"
    }
   ]
  },
  {
   "title": "VPN daemon memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(gw_vpn_memory_usage {appliance_name=\"lhr - purple80\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "avg_over_time(gw_vpn_memory_usage {appliance_name=\"lhr - purple81\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "VPN daemon memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(gw_vpn_memory_usage {appliance_name=\"got - purple1\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "avg_over_time(gw_vpn_memory_usage {appliance_name=\"got - purple2\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "VPN daemon memory usage per user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(gw_vpn_memory_usage {appliance_name=\"lhr - purple80\"} [$__interval]) / avg_over_time(gw_vpn_sessions {appliance_name=\"lhr - purple80\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "avg_over_time(gw_vpn_memory_usage {appliance_name=\"lhr - purple81\"} [$__interval]) / avg_over_time(gw_vpn_sessions {appliance_name=\"lhr - purple81\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "VPN daemon memory usage per user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(gw_vpn_memory_usage {appliance_name=\"got - purple1\"} [$__interval]) / avg_over_time(gw_vpn_sessions {appliance_name=\"got - purple1\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "avg_over_time(gw_vpn_memory_usage {appliance_name=\"got - purple2\"} [$__interval]) / avg_over_time(gw_vpn_sessions {appliance_name=\"got - purple2\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "SPA UDP traffic flow errors",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "abs(increase(apn_spa_packets {type=\"authorized\",proto=\"udp-dns\",appliance_name=\"lhr - purple80\"} [1h]) - ignoring(proto) increase(apn_spa_packets {type=\"authorized\",proto=\"udp-dtls\",appliance_name=\"lhr - purple80\"} [1h]))",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "abs(increase(apn_spa_packets {type=\"authorized\",proto=\"udp-dns\",appliance_name=\"lhr - purple81\"} [1h]) - ignoring(proto) increase(apn_spa_packets {type=\"authorized\",proto=\"udp-dtls\",appliance_name=\"lhr - purple81\"} [1h]))",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "abs(increase(apn_spa_packets {type=\"authorized\",proto=\"udp-dns\",appliance_name=\"got - purple1\"} [1h]) - ignoring(proto) increase(apn_spa_packets {type=\"authorized\",proto=\"udp-dtls\",appliance_name=\"got - purple1\"} [1h]))",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "abs(increase(apn_spa_packets {type=\"authorized\",proto=\"udp-dns\",appliance_name=\"got - purple2\"} [1h]) - ignoring(proto) increase(apn_spa_packets {type=\"authorized\",proto=\"udp-dtls\",appliance_name=\"got - purple2\"} [1h]))",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "Ignored UDP packets received (DoS monitoring) ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(apn_spa_packets {appliance_name=\"lhr - purple80\",type=\"ignored\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "increase(apn_spa_packets {appliance_name=\"lhr - purple81\",type=\"ignored\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "increase(apn_spa_packets {appliance_name=\"got - purple1\",type=\"ignored\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "increase(apn_spa_packets {appliance_name=\"got - purple2\",type=\"ignored\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "Invalid TCP packets received (DoS monitoring) ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(apn_spa_packets {appliance_name=\"lhr - purple80\",proto=\"tcp\",type=\"invalid\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "increase(apn_spa_packets {appliance_name=\"lhr - purple81\",proto=\"tcp\",type=\"invalid\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "increase(apn_spa_packets {appliance_name=\"got - purple1\",proto=\"tcp\",type=\"invalid\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "increase(apn_spa_packets {appliance_name=\"got - purple2\",proto=\"tcp\",type=\"invalid\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "DNS forwarder activity per hour - lhr - purple80 ",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 105 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gw_dns_forwarder_query {appliance_name=\"lhr - purple80\",proto=\"ipv4\",type=\"a\"} [1h])*3600",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "DNS forwarder activity per hour - got - purple1",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 105 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gw_dns_forwarder_query {appliance_name=\"got - purple1\",proto=\"ipv4\",type=\"a\"} [1h])*3600",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "DNS forwarder activity per hour - lhr - purple81 ",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 109 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gw_dns_forwarder_query {appliance_name=\"lhr - purple81\",proto=\"ipv4\",type=\"a\"} [1h])*3600",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "DNS forwarder activity per hour - got - purple2 ",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 109 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gw_dns_forwarder_query {appliance_name=\"got - purple2\",proto=\"ipv4\", type=\"a\"} [1h])*3600",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "DNS resolver activity per hour - lhr - purple80",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 113 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gw_dns_resolver_query {appliance_name=\"lhr - purple80\",type=\"a\"} [1h])*3600",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "DNS resolver activity per hour - got - purple1 ",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 10, "y": 113 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gw_dns_resolver_query {appliance_name=\"got - purple1\",type=\"a\"} [1h])*3600",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "DNS resolver activity per hour - lhr - purple81",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 116 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gw_dns_resolver_query {appliance_name=\"lhr - purple81\",type=\"a\"} [1h])*3600",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "DNS resolver activity per hour - got - purple2 ",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 10, "y": 116 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gw_dns_resolver_query {appliance_name=\"got - purple2\",type=\"a\"} [1h])*3600",
     "legendFormat": "{{result}}"
    }
   ]
  }
 ]
}