{
 "title": "Controller",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "UserLicenses",
    "label": "User Licenses",
    "query": {
     "query": "query_result(ctrl_license_entitled_users{job=\"purple10\"})"
    }
   },
   {
    "name": "ippool",
    "label": "IP Pool",
    "query": {
     "query": "ctrl_ip_pool_total{name=~\".*v4\"}"
    }
   },
   {
    "name": "ippoolsize",
    "label": "IP Pool Size",
    "query": {
     "query": "query_result(ctrl_ip_pool_total{job=~\"$ippool\",name=~\".*v4\"})"
    }
   },
   {
    "name": "PortalLicenses",
    "label": "Portal Licenses",
    "query": {
     "query": "query_result(ctrl_license_entitled_portal_users{job=\"purple10\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><center><u>Controller Health Dashboard"
   }
  },
  {
   "title": "Purple 10",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sdp_appliance_function_status{job=\"purple10\"}",
     "legendFormat": "Status"
    },
    {}
   ]
  },
  {
   "title": "Purple 11",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sdp_appliance_function_status{job=\"purple11\"}",
     "legendFormat": "Status"
    },
    {}
   ]
  },
  {
   "title": "Purple 40",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sdp_appliance_function_status{job=\"purple10\"}",
     "legendFormat": "Status"
    },
    {}
   ]
  },
  {
   "title": "Disk usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sdp_appliance_disk_usage_percent{job=\"purple10\"}",
     "legendFormat": "Purple 10"
    },
    {
     "expr": "sdp_appliance_disk_usage_percent{job=\"purple11\"}",
     "legendFormat": "Purple 11"
    },
    {
     "expr": "sdp_appliance_disk_usage_percent{job=\"purple40\"}",
     "legendFormat": "Purple 40"
    }
   ]
  },
  {
   "title": "SPA UDP traffic flow errors",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "abs( increase(spa_dtls_authorized {job=\"purple10\"} [1d]) -  increase(spa_dns_authorized {job=\"purple10\"} [1d]) )",
     "legendFormat": "Purple 10"
    },
    {
     "expr": "abs( increase(spa_dtls_authorized {job=\"purple11\"} [1d]) -  increase(spa_dns_authorized {job=\"purple11\"} [1d]) )",
     "legendFormat": "Purple 11"
    },
    {
     "expr": "abs( increase(spa_dtls_authorized {job=\"purple40\"} [1d]) -  increase(spa_dns_authorized {job=\"purple40\"} [1d]) )",
     "legendFormat": "Purple 40"
    }
   ]
  },
  {
   "title": "Invalid UDP packets received (DoS monitoring) ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ipv4_invalid_udp_dns_packets {job='purple10'} [$__interval]) + increase(ipv4_invalid_udp_dtls_packets {job='purple10'} [$__interval])",
     "legendFormat": "Purple 10"
    },
    {
     "expr": "increase(ipv4_invalid_udp_dns_packets {job='purple11'} [$__interval]) + increase(ipv4_invalid_udp_dtls_packets {job='purple11'} [$__interval])",
     "legendFormat": "Purple 11"
    },
    {
     "expr": "increase(ipv4_invalid_udp_dns_packets {job='purple40'} [$__interval]) + increase(ipv4_invalid_udp_dtls_packets {job='purple40'} [$__interval])",
     "legendFormat": "Purple 40"
    }
   ]
  },
  {
   "title": "Logs waiting for network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "avg_over_time (audit_logs_read {job=\"purple10\"} [$__interval])-avg_over_time(audit_logs_removed {job=\"purple10\"} [$__interval])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "avg_over_time (audit_logs_read {job=\"purple11\"} [$__interval])-avg_over_time(audit_logs_removed {job=\"purple11\"} [$__interval])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "avg_over_time (audit_logs_read {job=\"purple40\"} [$__interval])-avg_over_time(audit_logs_removed {job=\"purple40\"} [$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average sign in time",
   "type": "timeseries",
   "description": "Average sign in time",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ctrl_client_authentication_average_time{controller=\"y\"}+ctrl_client_authorization_average_time{controller=\"y\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Distribution - Authorizations",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ctrl_client_authorization_total{controller=\"y\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Controller Authorizations per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(ctrl_client_authorization_total{controller=\"y\"}[$__interval])*60*60",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum(rate(ctrl_client_authorization_total{controller=\"y\"}[$__interval])*60*60)",
     "legendFormat": "All Controllers"
    }
   ]
  },
  {
   "title": "IP v4 pool size and utilisation >>>",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "ctrl_ip_pool_total{name=~\".*v4\"}"
    }
   ]
  },
  {
   "title": "Purple 10",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ctrl_ip_pool_currently_used{job=\"purple10\",name=~\".*v4\"}+ctrl_ip_pool_reserved{job=\"purple10\",name=~\".*v4\"})/ctrl_ip_pool_total{job=\"purple10\",name=~\".*v4\"}*100"
    }
   ]
  },
  {
   "title": "Purple 11",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ctrl_ip_pool_currently_used{job=\"purple11\",name=~\".*v4\"}+ctrl_ip_pool_reserved{job=\"purple11\",name=~\".*v4\"})/ctrl_ip_pool_total{job=\"purple11\",name=~\".*v4\"}*100"
    }
   ]
  },
  {
   "title": "Purple 40",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ctrl_ip_pool_currently_used{job=\"purple40\",name=~\".*v4\"}+ctrl_ip_pool_reserved{job=\"purple40\",name=~\".*v4\"})/ctrl_ip_pool_total{job=\"purple40\",name=~\".*v4\"}*100"
    }
   ]
  },
  {
   "title": "User License Utilisation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ctrl_license_used_users{job=\"purple10\"}/ctrl_license_entitled_users{job=\"purple10\"}*100"
    }
   ]
  },
  {
   "title": "Portal License Utilisation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ctrl_license_used_portal_users{job=\"purple10\"}/ctrl_license_entitled_portal_users{job=\"purple10\"}*100"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ctrl_license_entitled_connector_groups{job=\"purple10\"}",
     "legendFormat": "Connector Groups Licenses"
    },
    {
     "expr": "ctrl_license_entitled_sites{job=\"purple10\"}",
     "legendFormat": "Sites Licenses"
    }
   ]
  }
 ]
}