{
 "title": "Gateway",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><center><u>Gateway Health Dashboard"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 2 },
   "options": {
    "content": "<h2><center>Heathrow</center>\n"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 8, "x": 8, "y": 2 }, "options": { "content": "<H2><center>Gothenburg\n" } },
  {
   "title": "Purple 80",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sdp_appliance_function_status{job=\"purple80\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Purple 81",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sdp_appliance_function_status{job=\"purple81\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Purple 1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sdp_appliance_function_status{job=\"purple1\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Purple 2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sdp_appliance_function_status{job=\"purple2\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "description": "Mean available memory usage",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100-(sdp_appliance_memory_available_bytes {job=\"purple80\"}/sdp_appliance_memory_total_bytes {job=\"purple80\"} *100)"
    },
    {
     "expr": "100-(sdp_appliance_memory_available_bytes {job=\"purple81\"}/sdp_appliance_memory_total_bytes {job=\"purple81\"} *100)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "description": "Mean available memory usage",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100-(sdp_appliance_memory_available_bytes {job=\"purple1\"}/sdp_appliance_memory_total_bytes {job=\"purple1\"} *100)"
    },
    {
     "expr": "100-(sdp_appliance_memory_available_bytes {job=\"purple2\"}/sdp_appliance_memory_total_bytes {job=\"purple2\"} *100)"
    }
   ]
  },
  {
   "title": "SPA UDP traffic flow errors",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "abs( increase(spa_dtls_authorized {job=\"purple80\"} [1d]) -  increase(spa_dns_authorized {job=\"purple80\"} [1d]) )",
     "legendFormat": "Purple 80"
    },
    {
     "expr": "abs( increase(spa_dtls_authorized {job=\"purple81\"} [1d]) -  increase(spa_dns_authorized {job=\"purple81\"} [1d]) )",
     "legendFormat": "Purple 81"
    }
   ]
  },
  {
   "title": "SPA UDP traffic flow errors",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "abs( increase(spa_dtls_authorized {job=\"purple1\"} [1d]) -  increase(spa_dns_authorized {job=\"purple1\"} [1d]) )",
     "legendFormat": "Purple 1"
    },
    {
     "expr": "abs( increase(spa_dtls_authorized {job=\"purple2\"} [1d]) -  increase(spa_dns_authorized {job=\"purple2\"} [1d]) )",
     "legendFormat": "Purple 2"
    }
   ]
  },
  {
   "title": "Gateways session split",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sdp_appliance_function_number_of_sessions {job=\"purple80\"}",
     "legendFormat": "P80"
    },
    {
     "expr": "sdp_appliance_function_number_of_sessions {job=\"purple81\"}",
     "legendFormat": "P81"
    }
   ]
  },
  {
   "title": "Gateways session split",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sdp_appliance_function_number_of_sessions {job=\"purple1\", name=\"gateway\"}",
     "legendFormat": "Purple 1"
    },
    {
     "expr": "sdp_appliance_function_number_of_sessions {job=\"purple2\", name=\"gateway\"}",
     "legendFormat": "Purple 2"
    }
   ]
  },
  {
   "title": "NIC throughputs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg_over_time(sdp_appliance_network_interface_rx_speed {job=\"purple80\"} [$__interval])/1000000",
     "legendFormat": "{{job}} rx {{name}}"
    },
    {
     "expr": "avg_over_time(sdp_appliance_network_interface_tx_speed {job=\"purple80\"} [$__interval])/1000000",
     "legendFormat": "{{job}} tx {{name}}"
    },
    {
     "expr": "avg_over_time(sdp_appliance_network_interface_rx_speed {job=\"purple81\"} [$__interval])/1000000",
     "legendFormat": "{{job}} rx {{name}}"
    },
    {
     "expr": "avg_over_time(sdp_appliance_network_interface_tx_speed {job=\"purple81\"} [$__interval])/1000000",
     "legendFormat": "{{job}} tx {{name}}"
    }
   ]
  },
  {
   "title": "NIC throughputs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg_over_time(sdp_appliance_network_interface_rx_speed {job=\"purple1\"} [$__interval])/1000000",
     "legendFormat": "{{job}} rx {{name}}"
    },
    {
     "expr": "avg_over_time(sdp_appliance_network_interface_tx_speed {job=\"purple1\"} [$__interval])/1000000",
     "legendFormat": "{{job}} tx {{name}}"
    },
    {
     "expr": "avg_over_time(sdp_appliance_network_interface_rx_speed {job=\"purple2\"} [$__interval])/1000000",
     "legendFormat": "{{job}} rx {{name}}"
    },
    {
     "expr": "avg_over_time(sdp_appliance_network_interface_tx_speed {job=\"purple2\"} [$__interval])/1000000",
     "legendFormat": "{{job}} tx {{name}}"
    }
   ]
  },
  {
   "title": "Logs waiting for network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "avg_over_time (audit_logs_read {job=\"purple80\"} [$__interval])-avg_over_time(audit_logs_removed {job=\"purple80\"} [$__interval])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "avg_over_time (audit_logs_read {job=\"purple81\"} [$__interval])-avg_over_time(audit_logs_removed {job=\"purple81\"} [$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Logs waiting for network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "targets": [
    {
     "expr": "avg_over_time (audit_logs_read {job=\"purple1\"} [$__interval])-avg_over_time(audit_logs_removed {job=\"purple1\"} [$__interval])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "avg_over_time (audit_logs_read {job=\"purple2\"} [$__interval])-avg_over_time(audit_logs_removed {job=\"purple2\"} [$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Firewall rules active",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "avg_over_time(vpn_total_ipv4_rules {job=\"purple80\"} [$__interval])\n",
     "legendFormat": "Purple 80 IPv4"
    },
    {
     "expr": "avg_over_time(vpn_total_ipv4_rules {job=\"purple81\"} [$__interval])",
     "legendFormat": "Purple 81 IPv4"
    },
    {
     "expr": "avg_over_time(vpn_total_ipv6_rules {job=\"purple80\"} [$__interval])",
     "legendFormat": "Purple 80 IPv6"
    },
    {
     "expr": "avg_over_time(vpn_total_ipv6_rules {job=\"purple81\"} [$__interval])",
     "legendFormat": "Purple 81 IPv6"
    }
   ]
  },
  {
   "title": "Firewall rules active",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "avg_over_time(vpn_total_ipv4_rules {job=\"purple1\"} [$__interval])",
     "legendFormat": "Purple 1 IPv4"
    },
    {
     "expr": "avg_over_time(vpn_total_ipv4_rules {job=\"purple2\"} [$__interval])",
     "legendFormat": "Purple 2 IPv4"
    },
    {
     "expr": "avg_over_time(vpn_total_ipv6_rules {job=\"purple1\"} [$__interval])",
     "legendFormat": "Purple 1 IPv6"
    },
    {
     "expr": "avg_over_time(vpn_total_ipv6_rules {job=\"purple2\"} [$__interval])",
     "legendFormat": "Purple 2 IPv6"
    }
   ]
  },
  {
   "title": "URL access connections active",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "avg_over_time(url_access_active_connections {job=\"purple80\"} [$__interval])\n",
     "legendFormat": "Purple 80"
    },
    {
     "expr": "avg_over_time(url_access_active_connections {job=\"purple81\"} [$__interval])",
     "legendFormat": "Purple 81"
    }
   ]
  },
  {
   "title": "URL access connections active",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
   "targets": [
    {
     "expr": "avg_over_time(url_access_active_connections {job=\"purple1\"} [$__interval])\n",
     "legendFormat": "Purple 1"
    },
    {
     "expr": "avg_over_time(url_access_active_connections {job=\"purple2\"} [$__interval])",
     "legendFormat": "Purple 2"
    }
   ]
  },
  {
   "title": "Entitlement token evaluations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "rate(audit_event {type=\"entitlement_token_evaluated\", job=\"purple80\"} [$__interval])*60",
     "legendFormat": "Purple 80"
    },
    {
     "expr": "rate(audit_event {type=\"entitlement_token_evaluated\", job=\"purple81\"} [$__interval])*60",
     "legendFormat": "Purple 81"
    }
   ]
  },
  {
   "title": "Entitlement token evaluations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "rate(audit_event {type=\"entitlement_token_evaluated\", job=\"purple1\"} [$__interval])*60",
     "legendFormat": "Purple 1"
    },
    {
     "expr": "rate(audit_event {type=\"entitlement_token_evaluated\", job=\"purple2\"} [$__interval])*60",
     "legendFormat": "Purple 2"
    }
   ]
  },
  {
   "title": "Event execution time",
   "type": "heatmap",
   "description": "3 most time consuming events to handle.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sdp_gateway_session_event_average_time {job=\"purple80\",name=\"reEvaluateConditions\"} /1000"
    },
    {
     "expr": "sdp_gateway_session_event_average_time {job=\"purple80\",name=\"updateTokens\"} /1000"
    },
    {
     "expr": "sdp_gateway_session_event_average_time {job=\"purple80\",name=\"login\"} /1000"
    },
    {
     "expr": "sdp_gateway_session_event_average_time {job=\"purple81\",name=\"reEvaluateConditions\"} /1000"
    },
    {
     "expr": "sdp_gateway_session_event_average_time {job=\"purple81\",name=\"updateTokens\"} /1000"
    },
    {
     "expr": "sdp_gateway_session_event_average_time {job=\"purple81\",name=\"login\"} /1000"
    }
   ]
  },
  {
   "title": "Event execution time",
   "type": "heatmap",
   "description": "3 most time consuming events to handle.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
   "targets": [
    {
     "expr": "sdp_gateway_session_event_average_time {job=\"purple1\",name=\"reEvaluateConditions\"} /1000"
    },
    {
     "expr": "sdp_gateway_session_event_average_time {job=\"purple1\",name=\"updateTokens\"} /1000"
    },
    {
     "expr": "sdp_gateway_session_event_average_time {job=\"purple1\",name=\"login\"} /1000"
    },
    {
     "expr": "sdp_gateway_session_event_average_time {job=\"purple2\",name=\"reEvaluateConditions\"} /1000"
    },
    {
     "expr": "sdp_gateway_session_event_average_time {job=\"purple2\",name=\"updateTokens\"} /1000"
    },
    {
     "expr": "sdp_gateway_session_event_average_time {job=\"purple2\",name=\"login\"} /1000"
    }
   ]
  },
  {
   "title": "DNS named look-ups per hour Purple 80",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nr_dns_query_a_success {job=\"purple80\"} [1h])*3600",
     "legendFormat": "success"
    },
    {
     "expr": "rate(nr_dns_query_a_error_not_found {job=\"purple80\"} [1h])*3600",
     "legendFormat": "not found"
    },
    {
     "expr": "rate(nr_dns_query_a_cancelled {job=\"purple80\"} [1h])*3600",
     "legendFormat": "cancelled"
    },
    {
     "expr": "rate(nr_dns_query_a_error_no_data {job=\"purple80\"} [1h])*3600",
     "legendFormat": "no data"
    },
    {
     "expr": "rate(nr_dns_query_a_error_timeout {job=\"purple80\"} [1h])*3600",
     "legendFormat": "timed out"
    }
   ]
  },
  {
   "title": "DNS named look-ups per hour Purple 1",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nr_dns_query_a_success {job=\"purple1\"} [1h])*3600",
     "legendFormat": "success"
    },
    {
     "expr": "rate(nr_dns_query_a_error_not_found {job=\"purple1\"} [1h])*3600",
     "legendFormat": "not found"
    },
    {
     "expr": "rate(nr_dns_query_a_cancelled {job=\"purple1\"} [1h])*3600",
     "legendFormat": "cancelled"
    },
    {
     "expr": "rate(nr_dns_query_a_error_no_data {job=\"purple1\"} [1h])*3600",
     "legendFormat": "no data"
    },
    {
     "expr": "rate(nr_dns_query_a_error_timeout {job=\"purple1\"} [1h])*3600",
     "legendFormat": "timed out"
    }
   ]
  },
  {
   "title": "DNS forwarder look-ups per hour Purple 80",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(dns_forwarder_ipv4_query_a_no_error {job=\"purple80\"} [1h])*3600",
     "legendFormat": "success"
    },
    {
     "expr": "rate(dns_forwarder_ipv4_query_a_not_found {job=\"purple80\"} [1h])*3600",
     "legendFormat": "not found"
    },
    {
     "expr": "rate(dns_forwarder_ipv4_query_a_no_error {job=\"purple80\"} [1h])*3600",
     "legendFormat": "error"
    },
    {
     "expr": "rate(dns_forwarder_ipv4_query_a_timed_out {job=\"purple80\"} [1h])*3600",
     "legendFormat": "timed out"
    }
   ]
  },
  {
   "title": "DNS forwarder look-ups per hour Purple 1",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(dns_forwarder_ipv4_query_a_no_error {job=\"purple1\"} [1h])*3600",
     "legendFormat": "success"
    },
    {
     "expr": "rate(dns_forwarder_ipv4_query_a_not_found {job=\"purple1\"} [1h])*3600",
     "legendFormat": "not found"
    },
    {
     "expr": "rate(dns_forwarder_ipv4_query_a_error {job=\"purple1\"} [1h])*3600",
     "legendFormat": "error"
    },
    {
     "expr": "rate(dns_forwarder_ipv4_query_a_timed_out {job=\"purple1\"} [1h])*3600",
     "legendFormat": "timed out"
    }
   ]
  }
 ]
}