{
 "title": "Portal",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Name", "label": "appliance_name", "query": { "query": "ptl_client" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><center><u>Portal Health Dashboard"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 2 },
   "options": { "content": "<H4><center>${Name}" },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "description": "Portal function health",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_function_status{func=~\".*ptl.*\",name=\"portal\"}",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Appliance health",
   "gridPos": { "h": 1, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_status{func=~\".*ptl.*\"}",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "NIC throughputs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg_over_time(apn_network_interface_rx_speed {job=\"portalaccess\"} [$__interval])",
     "legendFormat": "{{job}} rx {{name}}"
    },
    {
     "expr": "avg_over_time(apn_network_interface_tx_speed {job=\"portalaccess\"} [$__interval])",
     "legendFormat": "{{job}} rx {{name}}"
    }
   ]
  },
  {
   "title": "Running Client instances",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ptl_client{type=\"running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Domains",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "targets": [
    { "expr": "ptl_dns_proxy_domain", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Used Client instances",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ptl_client{type=\"used\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ptl_client{type=\"running\"}",
     "legendFormat": "{{running}}"
    }
   ]
  },
  {
   "title": "Average CPU usage % (1 min)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(apn_cpu_usage_percent{job=\"portalaccess\"} [$__interval])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Hourly DNS Proxy activity (a)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(ptl_dns_proxy_query {type=\"a\",result=\"timedout\"} [1h])+ ignoring (result) increase (ptl_dns_proxy_query {type=\"a\",result=\"notfound\"} [1h]) + ignoring (result) increase(ptl_dns_proxy_query {type=\"a\",result=\"error\"} [1h])",
     "legendFormat": "DNS failures"
    },
    {
     "expr": "increase(ptl_dns_proxy_query {type=\"a\",result=\"success\"} [1h]) + ignoring (result) increase (ptl_dns_proxy_query {type=\"a\",result=\"cache\"} [1h])",
     "legendFormat": "DNS results"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "description": "Mean available memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apn_memory {job=\"portalaccess\",measure=\"percent\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Hourly DNS Proxy activity (aaaa)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(ptl_dns_proxy_query {type=\"aaaa\",result=\"timedout\"} [1h])+ ignoring (result) increase (ptl_dns_proxy_query {type=\"aaaa\",result=\"notfound\"} [1h]) + ignoring (result) increase(ptl_dns_proxy_query {type=\"aaaa\",result=\"error\"} [1h])",
     "legendFormat": "DNS failures"
    },
    {
     "expr": "increase(ptl_dns_proxy_query {type=\"aaaa\",result=\"success\"} [1h]) + ignoring (result) increase (ptl_dns_proxy_query {type=\"aaaa\",result=\"cache\"} [1h])",
     "legendFormat": "DNS results"
    }
   ]
  }
 ]
}