{
 "title": "Controller",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "UserLicenses",
    "label": "User Licenses",
    "query": {
     "query": "query_result(ctrl_license_entitled_users{job=\"purple10\"})"
    }
   },
   {
    "name": "ippool",
    "label": "IP Pool",
    "query": {
     "query": "ctrl_ip_pool_total{name=~\".*v4\"}"
    }
   },
   {
    "name": "ippoolsize",
    "label": "IP Pool Size",
    "query": {
     "query": "query_result(ctrl_ip_pool_total{job=~\"$ippool\",name=~\".*v4\"})"
    }
   },
   {
    "name": "PortalLicenses",
    "label": "Portal Licenses",
    "query": {
     "query": "query_result(ctrl_license_entitled_portal_users{job=\"purple10\"})"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><center><u>Controller Health Dashboard"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_function_status{job=\"purple10\", name=\"controller\"}",
     "legendFormat": "{{}}"
    }
   ]
  },
  {
   "title": "Distribution of authorizations",
   "type": "piechart",
   "description": "Checking the balance between the Controllers",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(ctr_client_authorization {measure=\"success\"} [4h])",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_function_status{job=\"purple40\", name=\"controller\"}",
     "legendFormat": " "
    },
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_function_status{job=\"purple11\", name=\"controller\"}",
     "legendFormat": " "
    },
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_function_status{job=\"purple10\", name=\"controller\"}",
     "legendFormat": " "
    },
    {}
   ]
  },
  {
   "type": "stat",
   "description": "Controller function health",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_function_status{appliance_name=\"aws - purple11\",name=\"controller\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Controller function health",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_function_status{appliance_name=\"aws - purple40\",name=\"controller\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Controller function health",
   "gridPos": { "h": 1, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_function_status{appliance_name=\"aws - purple10\",name=\"controller\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Appliance health",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_status{appliance_name=\"aws - purple11\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Appliance health",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_status{appliance_name=\"aws - purple40\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Appliance health",
   "gridPos": { "h": 1, "w": 6, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apn_status{appliance_name=\"aws - purple10\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs being successfully exported (per 5min)",
   "type": "stat",
   "description": "Indicates activity and verifies connection behind the appliances",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(apn_audit_logs {func=~.\".*ctr.*\",type=\"removed\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "Average CPU usage % (1 min)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(apn_cpu_usage_percent{func=~\".*ctr.*\"} [$__interval])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "ctr_threads{measure=\"current\"}",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "apn_memory {measure=\"percent\",job=\"purple40\"}",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "apn_memory {measure=\"percent\",job=\"purple11\"}",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "apn_memory {measure=\"percent\",job=\"purple10\"}",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "ctr_database_size {appliance_name=\"aws - purple10\"} /1000000",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "apn_disk {measure=\"percent\",func=~\".*ctr.*\"}",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "SPA UDP traffic flow errors",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "abs(increase(apn_spa_packets {type=\"authorized\",proto=\"udp-dns\",appliance_name=\"aws - purple40\"} [1h]) - ignoring(proto) increase(apn_spa_packets {type=\"authorized\",proto=\"udp-dtls\",appliance_name=\"aws - purple40\"} [1h]))",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "abs(increase(apn_spa_packets {type=\"authorized\",proto=\"udp-dns\",appliance_name=\"aws - purple10\"} [1h]) - ignoring(proto) increase(apn_spa_packets {type=\"authorized\",proto=\"udp-dtls\",appliance_name=\"aws - purple10\"} [1h]))",
     "legendFormat": "{{appliance_name}}"
    },
    {
     "expr": "abs(increase(apn_spa_packets {type=\"authorized\",proto=\"udp-dns\",appliance_name=\"aws - purple11\"} [1h]) - ignoring(proto) increase(apn_spa_packets {type=\"authorized\",proto=\"udp-dtls\",appliance_name=\"aws - purple11\"} [1h]))",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "Ignored UDP packets received (DoS monitoring) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(apn_spa_packets {func=~\".*ctr.*\",type=\"ignored\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "Invalid TCP packets received (DoS monitoring) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(apn_spa_packets {func=~\".*ctr.*\",proto=\"tcp\",type=\"invalid\"} [$__interval])",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "Average sign in time",
   "type": "timeseries",
   "description": "Average sign in time",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ctr_client_authentication {measure=\"average_time\"} + ctr_client_authorization {measure=\"average_time\"}",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "Failed Authentications per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(ctr_client_authentication {measure=\"error\"}[$__interval])*60*60",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "Authorizations per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(ctr_client_authorization {measure=\"success\"}[$__interval])*60*60",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "IP v4 pool size",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "ctr_ip_pool {usage=\"total\",name=~\".*4.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IPv4 pool usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ctr_ip_pool{usage=\"current\",name=~\".*v4\"}+ignoring (usage) ctr_ip_pool{usage=\"reserved\",name=~\".*v4\"})/ignoring (usage) ctr_ip_pool{usage=\"total\",name=~\".*v4\"}*100",
     "legendFormat": "{{appliance_name}}"
    }
   ]
  },
  {
   "title": "License Utilisation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ctr_license {appliance_name=\"aws - purple10\",measure=\"used\"} / ignoring (measure) ctr_license {appliance_name=\"aws - purple10\",measure=\"entitled\"} *100",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}